### ISSUE TITLE
Run nginx in a separate docker container

### ISSUE THREAD

**Issue by jtoss** [meerkat-cv/annotator-supreme#13]
Current docker-compose runs nginx and flask application in the same container. 
To-do:
- run the nginx in its own container
- have a shared volume to store the statics

**Comment by jtoss** [comment]
Work in progress in branch [ngnix_docker](https://github.com/meerkat-cv/annotator-supreme/tree/ngnix_docker) .

**Comment by gustavofuhr** [comment]
What we need to close this @jtoss ?
